### ISSUE TITLE
set color for different CodeRoute

### ISSUE THREAD

**Issue by hetheclif** [JoanMartin/trackanimation#2]
I find the lines of every CodeRoutes are all in blue, how can I set different colors for them?

**Comment by JoanMartin** [comment]
Hi @hetheclif,

you can do something like this

```python
input_directory = "example-routes/ibiza.csv"
ibiza_trk = trackanimation.readTrack(input_directory)
ibiza_trk = ibiza_trk.timeVideoNormalize(time=10, framerate=10)
ibiza_trk = ibiza_trk.setColors('CodeRoute', individual_tracks=False)

fig = AnimationTrack(df_points=ibiza_trk, dpi=300, bg_map=True, map_transparency=0.5)
fig.makeVideo(output_file='coloring-map-by-track', framerate=10, linewidth=1.0)
```

and the result will be:

![image](https://user-images.githubusercontent.com/15080096/38459580-9f0f3f6a-3aab-11e8-9987-1834e0607c45.png)

The important line for what you want to do is:
`ibiza_trk = ibiza_trk.setColors('CodeRoute', individual_tracks=False)`

This function takes the minimum and maximum of a metric in a group and sets a color for each value based on that minimum and maximum.  The parameter **individual_tracks** is a boolean to specify if you want that the group is conformed for all the tracks of your dataframe (set it to False) or if you want to color each track individually based on the minimum and maximum of each track (set it to True). This is useful if you want, for example, to analyze the **Speed** of each track individually or all tracks as a whole.

So, in this case, you have to specify **CodeRoute** as the metric and **individual_tracks = False** to set a color to each track.

As you can see in the picture, the color between some tracks are imperceptible because the RGB for a value is calculated based on the minimum and maximum. I am improving this function to make the difference between values greater.

For the moment, what you can do if you want a best result is create an incremental value based on your route codes:

```python
ibiza_trk.df['CodeRoute_incremental'] = pd.factorize(
    ibiza_trk.df['CodeRoute'])[0].astype(np.uint16)
ibiza_trk = ibiza_trk.setColors('CodeRoute_incremental', individual_tracks=False)
```

And the result will be:

![image](https://user-images.githubusercontent.com/15080096/38459831-5309e1e8-3aaf-11e8-9042-a2b8f33e77ac.png)


Regards! =)
